
GET http://localhost:3003/user/teste

####

POST http://localhost:3003/user/signup
Content-Type: application/json

{   
    "name": "Gabriel",
    "email": "gabriel3@gmail.com",
    "password": "123456"
}

####

POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "gabriel2@gmail.com",
    "password": "123456"
}

####

# Requisição com json

POST http://localhost:3003/product/add
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJiMzk0Y2E3LWZjM2ItNDRkZC05Y2UwLTdiYmJkNGY2YzI3MyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3Nzg0MjgyOCwiZXhwIjoxNjc3OTI5MjI4fQ.ZTWZm1CZhwj2QabwpBzTkTvltYPWQVxjqhAWaG70iaU

{
    "product": {
        "id": "1",
        "name": "Camiseta infantil",
        "price": 49.99,
        "description": "Camiseta de seda com estampa floral",
        "idUser": "9be0620c-ec02-4bf3-9d81-c244fc5a43c3",
        "tags": [
            {"tag": "Roupas"},
            {"tag":"Feminino"},
            {"tag":"Verão"}
        ]
    }
}

###
# Requisição com xml

POST http://localhost:3003/product/add
Content-Type: text/xml
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJiMzk0Y2E3LWZjM2ItNDRkZC05Y2UwLTdiYmJkNGY2YzI3MyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3Nzg0MjgyOCwiZXhwIjoxNjc3OTI5MjI4fQ.ZTWZm1CZhwj2QabwpBzTkTvltYPWQVxjqhAWaG70iaU



<?xml version="1.0" encoding="UTF-8"?>

<product>
    <id>1</id>
    <name>Camiseta Feminina</name>
    <price>49.99</price>
    <description>Camiseta de algodão com estampa floral</description>
    <idUser>9be0620c-ec02-4bf3-9d81-c244fc5a43c3</idUser>
    <tags>
         <tag>Roupas</tag>
        <tag>Feminino</tag>
        <tag>Verão</tag>
    </tags>
</product>
