
GET http://localhost:3003/user/teste

####

POST http://localhost:3008/user/signup
Content-Type: application/json

{   
    "name": "Gabriel",
    "email": "teste11@gmail.com",
    "password": "123456"
}

####

POST http://localhost:3008/user/login
Content-Type: application/json

{
    "email": "admin1@StockKeeper.com",
    "password": "123456"
}

####

# Requisição com json

POST http://localhost:3008/product/add
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMTIiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzgyMzE5MjAsImV4cCI6MTY3ODMxODMyMH0.q0MnaKb7j5_YLIs3YpAWR72dMdW1nVWWW1xCyNbmYaA

{
    "product": {
        "id": "1",
        "name": "Camiseta Masculina",
        "price": 49.99,
        "description": "Camiseta de seda com estampa floral",
        "idUser": "1212",
        "tags": [
            {"tag": "Roupas"},
            {"tag":"Feminino"},
            {"tag":"Verão"}
        ]
    }
}

###
# Requisição com xml

POST http://localhost:3003/product/add
Content-Type: text/xml
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..yvedQXaV6suCluvR06xbqQfc46gI4O3Ock3bsv75x-0



<?xml version="1.0" encoding="UTF-8"?>

<product>
    <id>1</id>
    <name>Camiseta Feminina de manga longa</name>
    <price>49.99</price>
    <description>Camiseta de algodão com estampa floral</description>
    <idUser>f9cbf278-46d2-4642-930f-a351942f361f</idUser>
    <tags>
        <tag>Roupas</tag>
        <tag>Feminino</tag>
        <tag>Verão</tag>
    </tags>
</product>
